#Justin Fraumeni
#zshrc

fpath+=("$HOME/.zsh/pure")

LS_COLORS='no=00;37:fi=00:di=34:ln=04;32:pi=40;33:so=01;35:bd=40;33;01:ex=31'

export LS_COLORS

zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

zstyle :prompt:pure:git:dirty color foreground

setopt APPEND_HISTORY
setopt SHARE_HISTORY



#location of history file
HISTFILE=~/.zsh_history
#lines in history file
HISTSIZE=10000
#lines saved in history
SAVEHIST=10000


#use vi key bindings in shell
bindkey -v

#OSX specific configuration
if [ "$(uname 2> /dev/null)" = "Darwin" ]; then
	PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
fi	

#always have directory colors
alias ls='ls --color=auto'

#consistent terminal behavior
TERM=xterm-256color
TERM=screen-256color       # for a tmux -2 session (also for screen)

#love this tool for search and replace
autoload -U zmv

zstyle :compinstall filename '/home/justin/.zshrc'
autoload -Uz compinit
compinit

autoload -U promptinit; promptinit
prompt pure

DISABLE_AUTO_TITLE="true"

