#Justin Fraumeni
#zshrc

setopt APPEND_HISTORY
setopt SHARE_HISTORY
# Lines configured by zsh-newuser-install

#location of history file
HISTFILE=~/.zsh_history
#lines in history file
HISTSIZE=10000
#lines saved in history
SAVEHIST=10000

#use vi key bindings in shell
bindkey -v

#OSX specific configuration
if [ "$(uname 2> /dev/null)" = "Darwin" ]; then
	PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
fi	

#always have directory colors
alias ls='ls --color=auto'

#consistent terminal behavior
TERM=xterm-256color

#love this tool for search and replace
autoload -U zmv

zstyle :compinstall filename '/home/justin/.zshrc'
autoload -Uz compinit
compinit


















